-- provides schema needed for gbif re-id embeddings

--
-- PostgreSQL database dump
--

\restrict xlrRELUhM86AQG4Vl5tJdC89E5TnadHrhHxZuGCgXIuDf95vDpP7fO4SuF2jzDx

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: gbif_embeddings; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE gbif_embeddings WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';


ALTER DATABASE gbif_embeddings OWNER TO postgres;

\unrestrict xlrRELUhM86AQG4Vl5tJdC89E5TnadHrhHxZuGCgXIuDf95vDpP7fO4SuF2jzDx
\connect gbif_embeddings
\restrict xlrRELUhM86AQG4Vl5tJdC89E5TnadHrhHxZuGCgXIuDf95vDpP7fO4SuF2jzDx

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: annotation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.annotation (
    id integer NOT NULL,
    bbox json NOT NULL,
    embedding public.vector(2152),
    image_id integer NOT NULL
);


ALTER TABLE public.annotation OWNER TO postgres;

--
-- Name: annotation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.annotation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.annotation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gbif_reference; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gbif_reference (
    id character varying(255) NOT NULL,
    taxonomy text
);


ALTER TABLE public.gbif_reference OWNER TO postgres;

--
-- Name: image; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.image (
    id integer NOT NULL,
    uri text NOT NULL,
    gbif_id character varying(255) NOT NULL
);


ALTER TABLE public.image OWNER TO postgres;

--
-- Name: image_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: annotation annotation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.annotation
    ADD CONSTRAINT annotation_pkey PRIMARY KEY (id);


--
-- Name: gbif_reference gbif_reference_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gbif_reference
    ADD CONSTRAINT gbif_reference_pkey PRIMARY KEY (id);


--
-- Name: image image_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.image
    ADD CONSTRAINT image_pkey PRIMARY KEY (id);


--
-- Name: image image_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.image
    ADD CONSTRAINT image_unique UNIQUE (uri, gbif_id);


--
-- Name: annotation annotation_image_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.annotation
    ADD CONSTRAINT annotation_image_id_fkey FOREIGN KEY (image_id) REFERENCES public.image(id);


--
-- Name: image image_gbif_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.image
    ADD CONSTRAINT image_gbif_id_fkey FOREIGN KEY (gbif_id) REFERENCES public.gbif_reference(id);


--
-- PostgreSQL database dump complete
--

\unrestrict xlrRELUhM86AQG4Vl5tJdC89E5TnadHrhHxZuGCgXIuDf95vDpP7fO4SuF2jzDx

